-- Create table Students 
CREATE TABLE STUDENTS ( 
    ID INT PRIMARY KEY, 
    NAME VARCHAR(255),
    EMAIL VARCHAR(255));

-- Create table Marks
CREATE TABLE MARKS ( 
    ID INT PRIMARY KEY );


-- Fill table Students with data
INSERT INTO STUDENTS VALUES(1,'Adam Jakistam', 'ajakistam@gmail.com');
INSERT INTO STUDENTS VALUES(2,'Jan Jakistam', 'jjakistam@gmail.com');
INSERT INTO STUDENTS VALUES(3,'Anna Jakistam', 'anjakistam@gmail.com');
INSERT INTO STUDENTS VALUES(4,'Tom Kielon', 'anjakistam@gmail.com');
INSERT INTO STUDENTS VALUES(5,'Gawel Niecny', 'anjakistam@gmail.com');


-- Fill table Marks with data
INSERT INTO MARKS VALUES(1);
INSERT INTO MARKS VALUES(2);
INSERT INTO MARKS VALUES(3);
INSERT INTO MARKS VALUES(4);
INSERT INTO MARKS VALUES(5);

-- BankApp BANKS table
CREATE TABLE BANK (
ID INT AUTO_INCREMENT NOT NULL,
NAME VARCHAR(255),
PRIMARY KEY(ID)
);

-- BankApp Clients table
CREATE TABLE CLIENTS (
	CLIENTS_ID INT AUTO_INCREMENT,
	CLIENTS_NAME VARCHAR(255),
	CLIENTS_GENDER VARCHAR(255),
	CLIENTS_CITY VARCHAR(255),
	PRIMARY KEY(CLIENTS_ID)
);

-- BankApp ACCOUNTS table
CREATE TABLE ACCOUNTS (
	ACCOUNTS_ID INT AUTO_INCREMENT,
	ACCOUNTS_CLIENT_ID INT, --TU MAJA BYC ID CLIENTOW POSIADACZY
							--DODAC KOLUMNE Z BANKIEM?
	ACCOUNTS_TYPE VARCHAR(1),
	ACCOUNTS_BALANCE INT,
	ACCOUNTS_OVERDRAFT INT,	
	PRIMARY KEY(ACCOUNTS_ID)
);

-- BankApp FILL Clients WITH DATA 
INSERT INTO CLIENTS ();



